### ISSUE TITLE
Add json template on Active Page 

### ISSUE THREAD

**Issue by SohaibAshraf1** [polotno-project/polotno-studio#21]
I'm receiving json data in response to an api. This contains the image url and the template json. Images are flawlessly mapping on getPreview. However, the problem is that I want the image to act as a template on onSelect so that the user may group and ungroup the pieces inside. Is it possible to add a json to the Onselect  so i can utilize it?

Here is my code:

  ```
          <ImagesGrid
                images={images}
                getPreview={(image) => window.location.origin + '/' + image.image}
                onSelect={async (image) => {
                    const altered = JSON.parse(image.template_json)
                    console.log("🚀 ~ file: TemplateLibrary.jsx ~ line 45 ~ onSelect={ ~ altered", altered)

                    const { width, height } = await getImageSize(window.location.origin + '/' + altered.template_json);
                    await store.activePage?.addElement({
                        type: "image",
                        src: window.location.origin + '/' + altered.template_json.pages[0].children, width, height,
                        x: pos ? pos.x : store.width / 2 - width / 2,
                        y: pos ? pos.y : store.height / 2 - height / 2,
                    });
                    store.loadJSON(altered)
                }}
                rowsNumber={2}
                loadMore={true}
                isLoading={isLoading}

            />
```

api response:

![JSON](https://user-images.githubusercontent.com/115225219/201347262-e6719040-1c95-45fe-9fd1-e57701ef1ee7.PNG)

**Comment by lavrton** [comment]
I don't understand your issue here. You just load JSON of template and user should be able to edit it. Do you want to keep old content?

**Comment by maisabek** [comment]
yes

**Comment by ADTC** [comment]
@lavrton I understand that templates are entire projects (which could have multiple pages) and so they are expected to replace ALL of the existing pages with the pages from templates.

But I was thinking more of "Layouts" than "Templates" where the so-called template would replace the _active_ page in the current project, **without discarding any of other existing pages**. (Or in another use case, it could add the template (even with multiple pages) as new pages after the active page.)

Is this possible by any chance? Instead of `store.loadJSON(json, saveHistory)` I hoped we had options like:

```js
store.loadJSON(
  json,
  { // an optional object with options
    saveHistory, // default: false
    applyMode:
      | 'overwrite' // default option, overwrite entire project
      | 'replace-active' // replace active page and insert page 2..n as new pages before next existing page if any or at end
      | 'insert-after-active'  // insert all template pages as new pages before next existing page if any or at end
  }
)
```

Barring the lack of such options, is it possible to do it manually by using `store.activePage` and `store.addPage()`? I wish there was a way to do `store.activePage.loadJSON(json)` or something.
